-- MySQL Script generated by MySQL Workbench
-- Sun Jul 11 11:12:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema asmjv5
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema asmjv5
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asmjv5` DEFAULT CHARACTER SET utf8mb4 ;
USE `asmjv5` ;

-- -----------------------------------------------------
-- Table `asmjv5`.`acounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asmjv5`.`acounts` (
  `Username` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `Password` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `Fullname` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Email` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Photo` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Activated` INT(11) NULL DEFAULT NULL,
  `Admin` INT(11) NULL DEFAULT NULL,
  `CreateDate` VARCHAR(45) NULL DEFAULT NULL,
  `Address` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`Username`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `asmjv5`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asmjv5`.`categories` (
  `IdCategory` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) CHARACTER SET 'utf8' NOT NULL,
  `Activated` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `asmjv5`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asmjv5`.`orders` (
  `IdOrder` INT(11) NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `CreateDate` VARCHAR(50) NULL DEFAULT NULL,
  `Address` VARCHAR(100) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Status` INT(11) NULL DEFAULT NULL,
  `Total` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrder`),
  INDEX `FK_orders_acounts` (`Username` ASC) VISIBLE,
  CONSTRAINT `FK_orders_acounts`
    FOREIGN KEY (`Username`)
    REFERENCES `asmjv5`.`acounts` (`Username`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `asmjv5`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asmjv5`.`products` (
  `IdProduct` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(50) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Image` VARCHAR(200) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `Price` FLOAT NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  `CreateDate` VARCHAR(50) NULL DEFAULT NULL,
  `Available` INT(11) NULL DEFAULT NULL,
  `IdCategory` INT(11) NULL DEFAULT NULL,
  `Descreption` VARCHAR(500) NULL DEFAULT NULL,
  `Saled` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdProduct`),
  INDEX `FK_products_categories` (`IdCategory` ASC) VISIBLE,
  CONSTRAINT `FK_products_categories`
    FOREIGN KEY (`IdCategory`)
    REFERENCES `asmjv5`.`categories` (`IdCategory`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `asmjv5`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asmjv5`.`order_details` (
  `IdOrderDetail` INT(11) NOT NULL AUTO_INCREMENT,
  `IdOrder` INT(11) NULL DEFAULT NULL,
  `IdProduct` INT(11) NULL DEFAULT NULL,
  `Price` FLOAT NULL DEFAULT NULL,
  `Quantity` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`IdOrderDetail`),
  INDEX `IdOrder` (`IdOrder` ASC) VISIBLE,
  INDEX `IdProduct` (`IdProduct` ASC) VISIBLE,
  CONSTRAINT `order_details_ibfk_1`
    FOREIGN KEY (`IdOrder`)
    REFERENCES `asmjv5`.`orders` (`IdOrder`),
  CONSTRAINT `order_details_ibfk_2`
    FOREIGN KEY (`IdProduct`)
    REFERENCES `asmjv5`.`products` (`IdProduct`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
